#
# Makefile.simple
# ngspread
#

NG_VERSION    := $(shell git describe --tags --always 2>/dev/null || echo unknown)
NG_GIT_HASH   := $(shell git rev-parse --short HEAD 2>/dev/null || echo unknown)
NG_BUILD_DATE := $(shell date -u '+%Y-%m-%dT%H:%M:%SZ')

CC      = gcc

CFLAGS  = -O2 -Wall -Wextra `pkg-config glib-2.0 --cflags` -std=c99 -fcommon


CPPFLAGS = -D_GNU_SOURCE -D_DEFAULT_SOURCE \
	 -Iinclude\
	 -Idaemon \
	 -Ilibspread \
	 -Ilibspread-util/include \
	 -Istdutil/src

CPPFLAGS += -D_GNU_SOURCE -D_DEFAULT_SOURCE
CPPFLAGS += -DNG_VERSION=\"$(NG_VERSION)\"
CPPFLAGS += -DNG_GIT_HASH=\"$(NG_GIT_HASH)\"
CPPFLAGS += -DNG_BUILD_DATE=\"$(NG_BUILD_DATE)\"

LDFLAGS =

LDLIBS  = `pkg-config glib-2.0 --libs` -lcrypt -ldl

DAEMON_OBJS = \
    daemon/spread.o \
    daemon/session.o \
    daemon/network.o \
    daemon/protocol.o \
    daemon/membership.o \
    daemon/groups.o \
    daemon/message.o \
    daemon/configuration.o \
    daemon/log.o \
    daemon/status.o \
    daemon/flow_control.o \
    daemon/auth-null.o \
    daemon/auth-ip.o \
    daemon/auth-pword.o \
    daemon/acm.o \
    daemon/acp-permit.o \
    daemon/ip_enum.o \
    daemon/y.tab.o \
    daemon/lex.yy.o \
    daemon/version.o


SPU_OBJS = \
    libspread-util/src/alarm.o \
    libspread-util/src/events.o \
    libspread-util/src/memory.o \
    libspread-util/src/spu_addr.o \
    libspread-util/src/data_link.o
    
STDUTIL_OBJS = \
    stdutil/src/stderror.o \
    stdutil/src/stdhash.o \
    stdutil/src/stdskl.o \
    stdutil/src/stdit.o \
    stdutil/src/stdutil.o \
    stdutil/src/stdarr.o \
    stdutil/src/stddll.o \
    stdutil/src/stdtime.o \
    stdutil/src/stdcarr.o \
    stdutil/src/stdthread.o
    

LIBSPREAD_OBJS = \
    libspread/sp.o \
    libspread/fl.o \
    libspread/scatp.o

all: spread spuser

spread: $(DAEMON_OBJS) $(LIBSPREAD_OBJS)  $(SPU_OBJS) $(STDUTIL_OBJS)
	$(CC) $(LDFLAGS) -o $@ $(DAEMON_OBJS) $(LIBSPREAD_OBJS) $(SPU_OBJS) $(STDUTIL_OBJS) $(LDLIBS)


spuser: examples/user.o $(LIBSPREAD_OBJS) $(SPU_OBJS) $(STDUTIL_OBJS)
	$(CC) $(LDFLAGS) -o $@ examples/user.o $(LIBSPREAD_OBJS) $(SPU_OBJS) $(STDUTIL_OBJS) $(LDLIBS)

daemon/lex.yy.o: daemon/lex.yy.c
	$(CC) $(CPPFLAGS) $(CFLAGS) \
	-Wno-unused-function \
	-Wno-misleading-indentation \
	-c -o $@ $<

%.o: %.c
	$(CC) $(CPPFLAGS) $(CFLAGS) -c -o $@ $<

clean:
	rm -f spread spuser
	rm -f daemon/*.o libspread/*.o


